=== alejandrogalvez0101/PROYECTO-INTERMODULAR-1-ASIR/LENGUAJE DE MARCAS/xml/modelo.dtd
<!ELEMENT academia (profesores, aulas, reservas)>
<!ATTLIST academia nombre CDATA #REQUIRED>

<!ELEMENT profesores (profesor+)>
<!ELEMENT profesor (nombre)>
<!ATTLIST profesor 
    id ID #REQUIRED
    especialidad CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT aulas (aula+)>
<!ELEMENT aula (nombre, capacidad)>
<!ATTLIST aula 
    id ID #REQUIRED
    tipo (Fisica|Online) "Fisica">
<!ELEMENT capacidad (#PCDATA)>

<!ELEMENT reservas (reserva*)>
<!ELEMENT reserva (curso, horario, estado)>
<!ATTLIST reserva 
    id ID #REQUIRED
    ref_pro IDREF #REQUIRED
    ref_aula IDREF #REQUIRED>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT horario (#PCDATA)>
<!ATTLIST horario fecha CDATA #REQUIRED>
<!ELEMENT estado (#PCDATA)>

=== alejandrogalvez0101/PROYECTO-INTERMODULAR-1-ASIR/LENGUAJE DE MARCAS/xml/reservas.xml
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/xsl" href="transform.xsl"?> 
<!DOCTYPE academia SYSTEM "modelo.dtd"> 
<academia nombre="IT Alex Academy"> 
     <profesores> 
          <profesor id="P01" especialidad="Redes y Ciberseguridad"> 
               <nombre>Juan Calvo</nombre> 
          </profesor> 
          <profesor id="P02" especialidad="Desarrollo de Software"> 
               <nombre>Marta García</nombre> 
          </profesor>
          <profesor id="P03" especialidad="Inteligencia artificial"> 
               <nombre>Luis Gonzalez</nombre> 
          </profesor> 
     </profesores> 

     <aulas> 
          <aula id="A01" tipo="Fisica"> 
               <nombre>Aula Formación - 1</nombre> 
               <capacidad>10</capacidad> 
          </aula> 
          <aula id="A02" tipo="Online"> 
               <nombre>Aula Online - 2</nombre> 
               <capacidad>50</capacidad> 
          </aula> 
          <aula id="A03" tipo="Online"> 
               <nombre>Aula Online - 3</nombre> 
               <capacidad>50</capacidad> 
          </aula> 
          <aula id="A04" tipo="Online"> 
               <nombre>Aula Online - 4</nombre> 
               <capacidad>50</capacidad> 
          </aula> 

     </aulas> 

     <reservas> 
          <reserva id="R001" ref_pro="P01" ref_aula="A01"> 
               <curso>Ethical Hacking Avanzado</curso> 
               <horario fecha="2026-05-10">09:00-11:00</horario> 
               <estado>Confirmada</estado> 
          </reserva> 
          <reserva id="R002" ref_pro="P02" ref_aula="A02"> 
               <curso>Java Full Stack Online</curso> 
               <horario fecha="2026-05-11">16:00-19:00</horario> 
               <estado>Pendiente</estado> 
          </reserva> 
     </reservas> 
</academia>
